lb1_initial_angle: '92'
lb2_initial_angle: '37'
lb3_initial_angle: '63'
lf1_initial_angle: '85'
lf2_initial_angle: '40'
lf3_initial_angle: '65'
rb1_initial_angle: '99'
rb2_initial_angle: '130'
rb3_initial_angle: '125'
rf1_initial_angle: '95'
rf2_initial_angle: '130'
rf3_initial_angle: '115'
