lb1_initial_angle: '90'
lb2_initial_angle: '90'
lb3_initial_angle: '90'
lf1_initial_angle: '90'
lf2_initial_angle: '90'
lf3_initial_angle: '90'
rb1_initial_angle: '90'
rb2_initial_angle: '90'
rb3_initial_angle: '90'
rf1_initial_angle: '90'
rf2_initial_angle: '90'
rf3_initial_angle: '90'
